#vamos a nutrir este deploy manifest
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: bitso-challenge-demo
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 10 # this is the fu#$@ number of replicas
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 3000m
            memory: 20Mi
          requests:
             cpu: 2000m
             memory: 20Mi  
